// mock-data.ts
import type { Missionary } from './types';

export const mockMissionaries: Missionary[] = [
  {
    id: '1',
    name: 'Familia',
    lastName: 'Ward',
    organization: 'Alianza Norteamérica',
    continent: 'north-america',
    location: { city: 'Dallas', country: 'Estados Unidos', latitude: 32.7767, longitude: -96.7970 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Equipo familiar que sirve en plantación de iglesias y discipulado.',
    media: [],
    contactInfo: [{ type: 'email', value: 'ward@example.org' }],
    specialNotes: 'Ministerio familiar; datos de ejemplo.',
    startDate: '2016-01-01',
    missionType: 'Apoyo a iglesias',
  },
  {
    id: '2',
    name: 'Gregorio',
    lastName: 'Avilez',
    organization: 'Red de Alcance Hispano',
    continent: 'north-america',
    location: { city: 'San Antonio', country: 'Estados Unidos', latitude: 29.4241, longitude: -98.4936 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Trabaja con comunidades hispanas en centros urbanos.',
    media: [],
    contactInfo: [{ type: 'email', value: 'gregorio@placeholder.org' }],
    specialNotes: 'Organización y contactos de ejemplo.',
    startDate: '2017-06-01',
    missionType: 'Evangelización',
  },
  {
    id: '3',
    name: 'Familia',
    lastName: 'Castillo',
    organization: 'Ministerios Fronterizos',
    continent: 'north-america',
    location: { city: 'El Paso', country: 'Estados Unidos', latitude: 31.7619, longitude: -106.4850 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Sirven a familias migrantes y comunidades fronterizas con ayuda práctica y espiritual.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2018-01-01',
    missionType: 'Ministerio comunitario',
  },
  {
    id: '4',
    name: 'Familia',
    lastName: 'Turriza',
    organization: 'Red de Familias Misioneras',
    continent: 'north-america',
    location: { city: 'Phoenix', country: 'Estados Unidos', latitude: 33.4484, longitude: -112.0742 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Discipulado familiar y ministerio infantil en barrios hispanos.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2016-05-01',
    missionType: 'Familia y niños',
  },
  {
    id: '5',
    name: 'Familia',
    lastName: 'Aviles',
    organization: 'Socios Regionales EE. UU.',
    continent: 'north-america',
    location: { city: 'Los Ángeles', country: 'Estados Unidos', latitude: 34.0522, longitude: -118.2437 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Familia socia regional que participa en alcance comunitario y apoyo a iglesias.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2015-09-01',
    missionType: 'Apoyo a iglesias',
  },
  {
    id: '6',
    name: 'Familia',
    lastName: 'Gomez',
    organization: 'Ministerios City Light',
    continent: 'north-america',
    location: { city: 'San Diego', country: 'Estados Unidos', latitude: 32.7157, longitude: -117.1611 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Evangelismo urbano y ministerio de discipulado.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2014-07-15',
    missionType: 'Evangelización y discipulado',
  },
  {
    id: '7',
    name: 'Familia',
    lastName: 'Santos',
    organization: 'Red de Iglesias Hispanas',
    continent: 'north-america',
    location: { city: 'Chicago', country: 'Estados Unidos', latitude: 41.8781, longitude: -87.6298 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Familia que sirve en roles pastorales y cuidado comunitario.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2013-03-01',
    missionType: 'Cuidado pastoral',
  },
  {
    id: '8',
    name: 'Familia',
    lastName: 'Flores',
    organization: 'Misiones Norteamérica',
    continent: 'north-america',
    location: { city: 'Houston', country: 'Estados Unidos', latitude: 29.7604, longitude: -95.3698 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Desarrollo comunitario y alcance barrial.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2019-02-01',
    missionType: 'Desarrollo comunitario',
  },
  {
    id: '9',
    name: 'Familia',
    lastName: 'Horn',
    organization: 'Socios Iglesia Heritage',
    continent: 'north-america',
    location: { city: 'Columbus', country: 'Estados Unidos', latitude: 39.9612, longitude: -82.9988 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Plantación de nuevas congregaciones y formación de líderes laicos.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2016-10-10',
    missionType: 'Plantación de iglesias',
  },
  {
    id: '10',
    name: 'Familia',
    lastName: 'Loewen',
    organization: 'Ministerios del Campo',
    continent: 'north-america',
    location: { city: 'Fargo', country: 'Estados Unidos', latitude: 46.8772, longitude: -96.7898 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Apoyo a iglesias rurales y desarrollo comunitario.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2012-04-01',
    missionType: 'Ministerio rural',
  },
  {
    id: '11',
    name: 'Familia',
    lastName: 'Esparza',
    organization: 'Ministerios Fronterizos',
    continent: 'north-america',
    location: { city: 'McAllen', country: 'Estados Unidos', latitude: 26.2034, longitude: -98.2300 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Trabaja con familias inmigrantes y congregaciones locales.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2018-09-01',
    missionType: 'Apoyo a migrantes',
  },
  {
    id: '12',
    name: 'Familia',
    lastName: 'Murillo',
    organization: 'Esperanza Urbana',
    continent: 'north-america',
    location: { city: 'Orlando', country: 'Estados Unidos', latitude: 28.5383, longitude: -81.3792 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Programas juveniles y discipulado familiar en la ciudad.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2017-08-01',
    missionType: 'Juventud y familia',
  },
  {
    id: '13',
    name: 'Familia',
    lastName: 'Robles',
    organization: 'Iglesia Bautista Libertad',
    continent: 'north-america',
    location: { city: 'Austin', country: 'Estados Unidos', latitude: 30.2672, longitude: -97.7431 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Dirigen adoración y discipulado; mentores de jóvenes músicos.',
    media: [],
    contactInfo: [{ type: 'email', value: 'manuel@iglesiabautista.com' }],
    specialNotes: 'Ministerio enfocado en adoración.',
    startDate: '2020-01-15',
    missionType: 'Ministerio de música',
  },
  {
    id: '14',
    name: 'Familia',
    lastName: 'Jorge Vara',
    organization: 'Red Hispana',
    continent: 'north-america',
    location: { city: 'San José', country: 'Estados Unidos', latitude: 37.3382, longitude: -121.8863 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Apoyo regional para plantación de iglesias y formación de liderazgo.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2015-05-01',
    missionType: 'Apoyo a iglesias',
  },
  {
    id: '15',
    name: 'Familia',
    lastName: 'Lilley',
    organization: 'Colectivo Esperanza Urbana',
    continent: 'north-america',
    location: { city: 'Portland', country: 'Estados Unidos', latitude: 45.5051, longitude: -122.6750 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Organización comunitaria y ministerio centrado en la ciudad.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2013-11-01',
    missionType: 'Ministerio urbano',
  },
  {
    id: '16',
    name: 'Familia',
    lastName: 'Lozano',
    organization: 'Ministerios de Barrio',
    continent: 'north-america',
    location: { city: 'San Francisco', country: 'Estados Unidos', latitude: 37.7749, longitude: -122.4194 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Alcance de barrio y evangelismo relacional.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2014-02-01',
    missionType: 'Desarrollo comunitario',
  },
  {
    id: '17',
    name: 'Familia',
    lastName: 'Hines',
    organization: 'Ministerios Heartland',
    continent: 'north-america',
    location: { city: 'Oklahoma City', country: 'Estados Unidos', latitude: 35.4676, longitude: -97.5164 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Plantación de iglesias en ciudades del medio oeste y apoyo a líderes locales.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2011-07-01',
    missionType: 'Plantación de iglesias',
  },
  {
    id: '18',
    name: 'Familia',
    lastName: 'Downs',
    organization: 'Alcance Familiar EE. UU.',
    continent: 'north-america',
    location: { city: 'Nashville', country: 'Estados Unidos', latitude: 36.1627, longitude: -86.7816 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Ministerio de música y juventud con énfasis en discipulado.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2012-09-01',
    missionType: 'Música y juventud',
  },
  {
    id: '19',
    name: 'Familia',
    lastName: 'Jimenez',
    organization: 'Socios Iglesia Hispana',
    continent: 'north-america',
    location: { city: 'Tampa', country: 'Estados Unidos', latitude: 27.9506, longitude: -82.4572 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Servicios sociales y participación comunitaria en barrios urbanos.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2016-03-01',
    missionType: 'Servicios sociales',
  },
  {
    id: '20',
    name: 'Familia',
    lastName: 'Avila',
    organization: 'City Light',
    continent: 'north-america',
    location: { city: 'Denver', country: 'Estados Unidos', latitude: 39.7392, longitude: -104.9903 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Ministerio urbano con énfasis en servir a los pobres.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2013-10-01',
    missionType: 'Ministerio urbano',
  },
  {
    id: '21',
    name: 'Familia',
    lastName: 'Lutrick',
    organization: 'Ministerios North Coast',
    continent: 'north-america',
    location: { city: 'San Francisco', country: 'Estados Unidos', latitude: 37.7749, longitude: -122.4194 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Ministerios centrados en discipulado que apoyan el crecimiento de iglesias.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2014-06-01',
    missionType: 'Discipulado',
  },
  {
    id: '22',
    name: 'Evangelista',
    lastName: '',
    organization: 'Fuerza de Evangelización',
    continent: 'north-america',
    location: { city: 'Charlotte', country: 'Estados Unidos', latitude: 35.2271, longitude: -80.8431 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Evangelismo regional y formación de equipos locales.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2019-01-01',
    missionType: 'Evangelización',
  },
  {
    id: '23',
    name: 'Dan',
    lastName: 'Meaders',
    organization: 'Ministerios Meaders',
    continent: 'north-america',
    location: { city: 'Raleigh', country: 'Estados Unidos', latitude: 35.7796, longitude: -78.6382 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Mentor y entrenador de pastores y líderes de iglesia.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2010-05-01',
    missionType: 'Desarrollo de liderazgo',
  },
  {
    id: '24',
    name: 'Carol',
    lastName: 'Cole-Williamson',
    organization: 'Ministerios Cole-Williamson',
    continent: 'north-america',
    location: { city: 'Minneapolis', country: 'Estados Unidos', latitude: 44.9778, longitude: -93.2650 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Desarrollo de liderazgo y programas de formación para iglesias.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2011-02-01',
    missionType: 'Formación',
  },
  {
    id: '25',
    name: 'Aroha',
    lastName: 'Ngata',
    organization: 'Alianza Ministerios Islas del Pacífico',
    continent: 'oceania',
    location: { city: 'Auckland', country: 'Nueva Zelanda', latitude: -37.0882, longitude: 174.6852 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Coordina esfuerzos ministeriales en naciones isleñas del Pacífico; preservación cultural y renovación espiritual.',
    media: [],
    contactInfo: [
      { type: 'email', value: 'aroha@pacificislandministry.org' },
      { type: 'facebook', value: 'https://facebook.com/aroha.ngata' },
    ],
    specialNotes: 'Especialista en ministerio pacífico; defensora de comunidades indígenas.',
    startDate: '2014-11-12',
    missionType: 'Ministerio isleño',
  },
  {
    id: '26',
    name: 'Familia',
    lastName: 'Maret',
    organization: 'Socios Caribeños',
    continent: 'central-america',
    location: { city: 'San Juan', country: 'Puerto Rico', latitude: 18.4655, longitude: -66.1057 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Equipo familiar en Puerto Rico que apoya a la iglesia y la comunidad.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2015-08-01',
    missionType: 'Apoyo a iglesias',
  },
  {
    id: '27',
    name: 'Familia',
    lastName: 'Acosta',
    organization: 'Alcance Centroamérica',
    continent: 'central-america',
    location: { city: 'Tegucigalpa', country: 'Honduras', latitude: 14.0723, longitude: -87.1921 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Sirven proyectos comunitarios y apoyo a iglesias en Honduras.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2016-03-01',
    missionType: 'Ministerio comunitario',
  },
  {
    id: '28',
    name: 'Familia',
    lastName: 'Murillo',
    organization: 'Red Familiar Centroamericana',
    continent: 'central-america',
    location: { city: 'Ciudad de Guatemala', country: 'Guatemala', latitude: 14.6349, longitude: -90.5069 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Familia que sirve en Guatemala con programas familiares y de cuidado a la iglesia.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2017-05-01',
    missionType: 'Ministerio familiar',
  },
  {
    id: '29',
    name: 'Familia',
    lastName: 'Hanson',
    organization: 'Alcance Insular',
    continent: 'central-america',
    location: { city: 'Belice', country: 'Belice', latitude: 17.5046, longitude: -88.1962 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Sirven a comunidades isleñas con educación y apoyo práctico.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2018-07-01',
    missionType: 'Desarrollo comunitario',
  },
  {
    id: '30',
    name: 'Familia',
    lastName: 'Flores',
    organization: 'Ministerios Familia Centroamérica',
    continent: 'central-america',
    location: { city: 'San Salvador', country: 'El Salvador', latitude: 13.6929, longitude: -89.2182 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Trabajan en plantaciones de iglesias centradas en la familia en Centroamérica.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2012-10-01',
    missionType: 'Plantación de iglesias',
  },
  {
    id: '31',
    name: 'Familia',
    lastName: 'Contreras',
    organization: 'Socios Centroamericanos',
    continent: 'central-america',
    location: { city: 'San José', country: 'Costa Rica', latitude: 9.9281, longitude: -84.0907 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Proyectos educativos y desarrollo comunitario en Costa Rica.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2013-12-01',
    missionType: 'Educación',
  },
  {
    id: '32',
    name: 'Familia',
    lastName: 'Alvarez',
    organization: 'Apoyo Regional a Iglesias',
    continent: 'central-america',
    location: { city: 'Managua', country: 'Nicaragua', latitude: 12.1364, longitude: -86.2514 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Apoya a iglesias locales y pequeños proyectos comunitarios.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2014-04-01',
    missionType: 'Ministerio comunitario',
  },
  {
    id: '33',
    name: 'Familia',
    lastName: 'Gonzalez',
    organization: 'Alcance Centroamérica',
    continent: 'central-america',
    location: { city: 'Ciudad de Panamá', country: 'Panamá', latitude: 8.9824, longitude: -79.5199 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Alcance comunitario e iniciativas de servicio social en Panamá.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2015-02-01',
    missionType: 'Servicios sociales',
  },
  {
    id: '34',
    name: 'Familia',
    lastName: 'Lopez',
    organization: 'Socios Centroamericanos',
    continent: 'central-america',
    location: { city: 'San Pedro Sula', country: 'Honduras', latitude: 15.5007, longitude: -88.0250 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Ministerio familiar centrado en el discipulado y cuidado de niños.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2016-01-01',
    missionType: 'Familia y niños',
  },
  {
    id: '35',
    name: 'Familia',
    lastName: 'Ramirez',
    organization: 'Socios Caribe y Centro',
    continent: 'central-america',
    location: { city: 'Santo Domingo', country: 'República Dominicana', latitude: 18.4861, longitude: -69.9312 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Ministerio familiar que sirve a iglesias en la República Dominicana.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2019-03-01',
    missionType: 'Apoyo a iglesias',
  },
  {
    id: '36',
    name: 'Familia',
    lastName: 'Romani',
    organization: 'Alianza Perú',
    continent: 'south-america',
    location: { city: 'Lima', country: 'Perú', latitude: -12.0464, longitude: -77.0428 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Trabaja con iglesias locales y capacitación comunitaria en Perú.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2014-09-01',
    missionType: 'Apoyo a iglesias',
  },
  {
    id: '37',
    name: 'Familia',
    lastName: 'Vallejo',
    organization: 'Alcance Brasil',
    continent: 'south-america',
    location: { city: 'São Paulo', country: 'Brasil', latitude: -23.5505, longitude: -46.6333 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Familia que realiza proyectos vocacionales y educativos en Brasil.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2015-07-01',
    missionType: 'Desarrollo comunitario',
  },
  {
    id: '38',
    name: 'Familia',
    lastName: 'Alanis',
    organization: 'Alcance andino',
    continent: 'south-america',
    location: { city: 'Quito', country: 'Ecuador', latitude: -0.1807, longitude: -78.4678 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Salud y educación en comunidades andinas.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2016-11-01',
    missionType: 'Salud',
  },
  {
    id: '39',
    name: 'Familia',
    lastName: 'Tully',
    organization: 'Socios Argentina',
    continent: 'south-america',
    location: { city: 'Buenos Aires', country: 'Argentina', latitude: -34.6037, longitude: -58.3816 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Plantación y desarrollo de liderazgo en Argentina.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2013-05-01',
    missionType: 'Plantación de iglesias',
  },
  {
    id: '40',
    name: 'Familia',
    lastName: 'Derreza',
    organization: 'Misión Colombia',
    continent: 'south-america',
    location: { city: 'Bogotá', country: 'Colombia', latitude: 4.7110, longitude: -74.0721 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Capacitan líderes y pastores en Colombia.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2017-04-01',
    missionType: 'Formación y liderazgo',
  },
  {
    id: '41',
    name: 'Familia',
    lastName: 'Gonzalez',
    organization: 'Socios Sudamérica',
    continent: 'south-america',
    location: { city: 'Santiago', country: 'Chile', latitude: -33.4489, longitude: -70.6693 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Proyectos comunitarios y apoyo a iglesias en Chile.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2012-02-01',
    missionType: 'Desarrollo comunitario',
  },
  {
    id: '42',
    name: 'Familia',
    lastName: 'Sanchez',
    organization: 'Alcance Bolivia',
    continent: 'south-america',
    location: { city: 'La Paz', country: 'Bolivia', latitude: -16.4897, longitude: -68.1193 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Apoya proyectos educativos y programas de alfabetización.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2018-05-01',
    missionType: 'Educación',
  },
  {
    id: '43',
    name: 'Familia',
    lastName: 'Rose',
    organization: 'Alcance Amazonía',
    continent: 'south-america',
    location: { city: 'Iquitos', country: 'Perú', latitude: -3.7437, longitude: -73.2516 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Trabaja con comunidades ribereñas y remotas en la Amazonía.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2019-06-01',
    missionType: 'Alcance remoto',
  },
  {
    id: '44',
    name: 'Familia',
    lastName: 'Gomez (SA)',
    organization: 'Ministerios Sudamérica',
    continent: 'south-america',
    location: { city: 'Medellín', country: 'Colombia', latitude: 6.2442, longitude: -75.5812 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Desarrolla empresas sociales y programas educativos locales.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2014-08-01',
    missionType: 'Desarrollo comunitario',
  },
  {
    id: '45',
    name: 'Familia',
    lastName: 'Smith',
    organization: 'Apoyo Sudamérica',
    continent: 'south-america',
    location: { city: 'Montevideo', country: 'Uruguay', latitude: -34.9011, longitude: -56.1645 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Equipo de apoyo para redes de iglesias en países del cono sur.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2011-01-01',
    missionType: 'Apoyo a iglesias',
  },
  {
    id: '46',
    name: 'Familia',
    lastName: 'Ellzey',
    organization: 'Misión Andes',
    continent: 'south-america',
    location: { city: 'Cusco', country: 'Perú', latitude: -13.5319, longitude: -71.9675 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Trabaja con comunidades indígenas con sensibilidad cultural y alianzas.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2013-09-01',
    missionType: 'Comunidad y cultura',
  },
  {
    id: '47',
    name: 'Familia',
    lastName: 'Kotvas',
    organization: 'Socios Amazonía',
    continent: 'south-america',
    location: { city: 'Manaus', country: 'Brasil', latitude: -3.1190, longitude: -60.0217 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Dirige clínicas y proyectos educativos en ciudades amazónicas.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2012-11-01',
    missionType: 'Salud y educación',
  },
  {
    id: '48',
    name: 'Familia',
    lastName: 'De La Fuente',
    organization: 'Alcance Sudamérica',
    continent: 'south-america',
    location: { city: 'Valparaíso', country: 'Chile', latitude: -33.0472, longitude: -71.6127 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Coordina proyectos comunitarios regionales y colaboración entre iglesias.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2016-12-01',
    missionType: 'Ministerio comunitario',
  },
  {
    id: '49',
    name: 'Familia',
    lastName: 'Puente',
    organization: 'Socios Reformados Europa',
    continent: 'europe',
    location: { city: 'Madrid', country: 'España', latitude: 40.4168, longitude: -3.7038 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Apoya la renovación de iglesias y trabajo en pequeños grupos por España.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2010-06-01',
    missionType: 'Renovación de iglesias',
  },
  {
    id: '50',
    name: 'Familia',
    lastName: 'Vogelpohl',
    organization: 'Red Alemana',
    continent: 'europe',
    location: { city: 'Hamburgo', country: 'Alemania', latitude: 53.5511, longitude: 9.9937 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Alianzas regionales en el norte de Alemania y países vecinos.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2012-03-01',
    missionType: 'Comunidad e iglesia',
  },
  {
    id: '51',
    name: 'Familia',
    lastName: 'Weimer',
    organization: 'Red Juvenil Europea',
    continent: 'europe',
    location: { city: 'Berlín', country: 'Alemania', latitude: 52.5200, longitude: 13.4050 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Mentoría juvenil y desarrollo de liderazgo en Alemania.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2014-05-01',
    missionType: 'Juventud y liderazgo',
  },
  {
    id: '52',
    name: 'Familia',
    lastName: 'Velasquez',
    organization: 'Socios Europeos',
    continent: 'europe',
    location: { city: 'Lyon', country: 'Francia', latitude: 45.7640, longitude: 4.8357 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Apoya a comunidades hispanohablantes en Europa occidental.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2016-01-01',
    missionType: 'Apoyo a iglesias',
  },
  {
    id: '53',
    name: 'Familia',
    lastName: 'Garza',
    organization: 'Misiones Europeas',
    continent: 'europe',
    location: { city: 'Londres', country: 'Reino Unido', latitude: 51.5074, longitude: -0.1278 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Ministerio urbano y alcance intercultural en Londres.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2015-04-01',
    missionType: 'Alcance urbano',
  },
  {
    id: '54',
    name: 'Familia',
    lastName: 'Stokes',
    organization: 'Apoyo Europa',
    continent: 'europe',
    location: { city: 'Ámsterdam', country: 'Países Bajos', latitude: 52.3702, longitude: 4.8952 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Equipo de apoyo para iglesias y redes en Europa.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2013-02-01',
    missionType: 'Apoyo a iglesias',
  },
  {
    id: '55',
    name: 'Familia',
    lastName: 'Velasquez Duplicate',
    organization: 'Socios Europeos',
    continent: 'europe',
    location: { city: 'París', country: 'Francia', latitude: 48.8566, longitude: 2.3522 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Listado duplicado en la diapositiva — asignado a París para el prototipo.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2016-01-01',
    missionType: 'Apoyo a iglesias',
  },
  {
    id: '56',
    name: 'Familia',
    lastName: 'Yetzer',
    organization: 'Socios Misión Europea',
    continent: 'europe',
    location: { city: 'Bruselas', country: 'Bélgica', latitude: 50.8503, longitude: 4.3517 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Trabaja en redes interiglesias y asociaciones ecuménicas.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2014-10-01',
    missionType: 'Redes',
  },
  {
    id: '57',
    name: 'Familia',
    lastName: 'Roberts',
    organization: 'Servicios Comunitarios Vietnam',
    continent: 'asia',
    location: { city: 'Ciudad Ho Chi Minh', country: 'Vietnam', latitude: 10.8231, longitude: 106.6297 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Coordina socorro en desastres y proyectos de servicio comunitario.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2017-08-01',
    missionType: 'Ayuda en desastres',
  },
  {
    id: '58',
    name: 'Familia',
    lastName: 'Kinoshita',
    organization: 'Fundación Misión Japón',
    continent: 'asia',
    location: { city: 'Tokio', country: 'Japón', latitude: 35.6762, longitude: 139.6503 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Plantación urbana enfocada en jóvenes profesionales en Japón.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2015-02-08',
    missionType: 'Plantación de iglesias',
  },
  {
    id: '59',
    name: 'Familia',
    lastName: 'Kongkaw',
    organization: 'Alcance Tailandia',
    continent: 'asia',
    location: { city: 'Bangkok', country: 'Tailandia', latitude: 13.7563, longitude: 100.5018 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Coordina ministerios asociados a través del sudeste asiático.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2016-09-20',
    missionType: 'Coordinación de redes',
  },
  {
    id: '60',
    name: 'Familia',
    lastName: 'Long',
    organization: 'Socios China',
    continent: 'asia',
    location: { city: 'Pekín', country: 'China', latitude: 39.9042, longitude: 116.4074 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Proyectos de desarrollo comunitario en áreas urbanas chinas.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2015-04-01',
    missionType: 'Servicio comunitario',
  },
  {
    id: '61',
    name: 'Familia',
    lastName: 'Rice',
    organization: 'Alianza India',
    continent: 'asia',
    location: { city: 'Nueva Delhi', country: 'India', latitude: 28.6139, longitude: 77.2090 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Empoderamiento femenino, educación y formación vocacional.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2019-01-15',
    missionType: 'Empoderamiento de mujeres',
  },
  {
    id: '62',
    name: 'Familia',
    lastName: 'Arnold',
    organization: 'Fideicomiso Educación Asia Sur',
    continent: 'asia',
    location: { city: 'Bombay', country: 'India', latitude: 19.0760, longitude: 72.8777 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Dirige programas educativos para niños desfavorecidos en Asia del Sur.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2013-10-05',
    missionType: 'Educación',
  },
  {
    id: '63',
    name: 'Familia',
    lastName: 'Gaddes',
    organization: 'Alianza Ministerios Islas del Pacífico',
    continent: 'oceania',
    location: { city: 'Auckland', country: 'Nueva Zelanda', latitude: -37.0882, longitude: 174.6852 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Coordina ministerios en islas del Pacífico con enfoque en preservación cultural.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2014-11-12',
    missionType: 'Ministerio isleño',
  },
  {
    id: '64',
    name: 'Familia',
    lastName: 'Allen',
    organization: 'Alcance Pacífico',
    continent: 'oceania',
    location: { city: 'Sídney', country: 'Australia', latitude: -33.8688, longitude: 151.2093 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Apoya ministerios isleños con formación y equipos de corto plazo.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2016-07-01',
    missionType: 'Ministerio comunitario',
  },
  {
    id: '65',
    name: 'Familia',
    lastName: 'Gray',
    organization: 'Socios Pacífico',
    continent: 'oceania',
    location: { city: 'Suva', country: 'Fiyi', latitude: -18.1416, longitude: 178.4419 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Proyectos de preservación cultural y formación de liderazgo comunitario.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2012-09-01',
    missionType: 'Comunidad y cultura',
  },
  {
    id: '66',
    name: 'Familia',
    lastName: 'Pridgen',
    organization: 'Misión Africana',
    continent: 'africa',
    location: { city: 'Lagos', country: 'Nigeria', latitude: 6.5244, longitude: 3.3792 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Coordina redes de iglesias y formación de liderazgo en África Occidental.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2016-04-12',
    missionType: 'Apoyo a iglesias',
  },
  {
    id: '67',
    name: 'Familia',
    lastName: 'Holmes',
    organization: 'Socios regionales África',
    continent: 'africa',
    location: { city: 'Nairobi', country: 'Kenia', latitude: -1.2921, longitude: 36.8219 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Gestiona clínicas y capacita a agentes de salud comunitarios.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2017-06-25',
    missionType: 'Salud',
  },
  {
    id: '68',
    name: 'Familia',
    lastName: 'Williams',
    organization: 'Red Misión Sudáfrica',
    continent: 'africa',
    location: { city: 'Johannesburgo', country: 'Sudáfrica', latitude: -26.2023, longitude: 28.0436 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Trabaja en proyectos de reconciliación y sanación comunitaria.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2018-03-10',
    missionType: 'Reconciliación',
  },
  {
    id: '69',
    name: 'Familia',
    lastName: 'Dobbins',
    organization: 'Alcance África',
    continent: 'africa',
    location: { city: 'Accra', country: 'Ghana', latitude: 5.6037, longitude: -0.1870 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Construcción y apoyo a escuelas y programas de formación de docentes.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2014-08-18',
    missionType: 'Educación',
  },
  {
    id: '70',
    name: 'Familia',
    lastName: 'Nunes',
    organization: 'Iniciativa Salud África',
    continent: 'africa',
    location: { city: 'Maputo', country: 'Mozambique', latitude: -25.9655, longitude: 32.5892 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Apoyo médico y formación en comunidades del sur de África.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2014-11-01',
    missionType: 'Salud',
  },
  {
    id: '71',
    name: 'Familia',
    lastName: 'Morris',
    organization: 'Socios África',
    continent: 'africa',
    location: { city: 'Kampala', country: 'Uganda', latitude: 0.3476, longitude: 32.5825 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Proyectos de desarrollo comunitario centrados en empoderamiento económico.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2013-06-01',
    missionType: 'Ministerio comunitario',
  },
  {
    id: '72',
    name: 'Familia',
    lastName: 'Shrader',
    organization: 'Equipos Misión África',
    continent: 'africa',
    location: { city: 'Dar es Salaam', country: 'Tanzania', latitude: -6.7924, longitude: 39.2083 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Dirige programas de liderazgo y cohortes de formación de corto plazo.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2015-09-01',
    missionType: 'Formación de liderazgo',
  },
  {
    id: '73',
    name: 'Familia',
    lastName: 'Porter',
    organization: 'Red Misiones África',
    continent: 'africa',
    location: { city: 'Douala', country: 'Camerún', latitude: 4.0511, longitude: 9.7679 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Apoya el desarrollo de iglesias y redes de pequeños grupos en África Central.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2012-11-03',
    missionType: 'Desarrollo de iglesias',
  },
  {
    id: '74',
    name: 'Familia',
    lastName: 'Kinsey',
    organization: 'Alcance Africano',
    continent: 'africa',
    location: { city: 'Freetown', country: 'Sierra Leona', latitude: 8.4606, longitude: -13.2317 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Programas de salud materno-infantil y educación sanitaria.',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2015-04-01',
    missionType: 'Educación en salud',
  },
  {
    id: '75',
    name: 'Familia',
    lastName: 'Faltaos',
    organization: 'Misión Africana',
    continent: 'africa',
    location: { city: 'El Cairo', country: 'Egipto', latitude: 30.0444, longitude: 31.2357 },
    profileImage: '/assets/MissionariesTest/mannyFacebook.jpg',
    description: 'Listado solo en la diapositiva 19 (diapositiva final de África).',
    media: [],
    contactInfo: [],
    specialNotes: '',
    startDate: '2014-01-01',
    missionType: 'Ministerio comunitario',
  },
];

// Helper functions to get missionaries
export const getMissionariesByContinent = (continent: string): Missionary[] => {
  return mockMissionaries.filter(m => m.continent === continent);
};

export const getMissionaryById = (id: string): Missionary | undefined => {
  return mockMissionaries.find(m => m.id === id);
};
