import { Missionary, ContinentInfo } from './types';

export const mockMissionaries: Missionary[] = [
  // North America (9)
  {
    id: '1',
    name: 'Manuel',
    lastName: 'Robles',
    organization: 'Iglesia Bautista Libertad',
    continent: 'north-america',
    location: {
      city: 'Austin',
      country: 'USA',
      state: 'Texas',
      latitude: 30.2672,
      longitude: -97.7431,
    },
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    description: 'Manuel serves in music ministry, leading worship and discipleship initiatives in central Texas. His passion is to inspire young musicians to serve the Lord through contemporary and traditional worship.',
    media: [
      { url: 'https://images.unsplash.com/photo-1511379938547-c1f69b13d835?w=300', title: 'Worship Service' },
      { url: 'https://images.unsplash.com/photo-1514613535308-eb5b1161184d?w=300', title: 'Music Ministry' },
    ],
    contactInfo: [
      { type: 'email', value: 'manuel@iglesiabautista.com' },
      { type: 'phone', value: '+1-512-555-0101' },
      { type: 'facebook', value: 'https://facebook.com/manuel.robles' },
    ],
    specialNotes: 'Leads weekly worship rehearsals and mentors young musicians in the faith.',
    startDate: '2020-01-15',
    missionType: 'Music Ministry',
  },
  {
    id: '2',
    name: 'Sarah',
    lastName: 'Thompson',
    organization: 'Global Outreach Ministries',
    continent: 'north-america',
    location: {
      city: 'Houston',
      country: 'USA',
      state: 'Texas',
      latitude: 29.7604,
      longitude: -95.3698,
    },
    profileImage: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400',
    description: 'Sarah is devoted to discipleship and women\'s ministry, helping women grow in their faith and mentor others. She leads Bible studies and spiritual formation groups throughout Houston.',
    media: [
      { url: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=300', title: 'Women\'s Ministry' },
      { url: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=300', title: 'Bible Study Group' },
    ],
    contactInfo: [
      { type: 'email', value: 'sarah.thompson@globaloutreach.org' },
      { type: 'phone', value: '+1-713-555-0202' },
      { type: 'instagram', value: 'https://instagram.com/sarahthompson' },
    ],
    specialNotes: 'Specializes in mentoring young women and leadership development.',
    startDate: '2018-06-01',
    missionType: 'Discipleship & Women\'s Ministry',
  },
  {
    id: '3',
    name: 'Diego',
    lastName: 'Vargas',
    organization: 'Amazon Mission Organization',
    continent: 'north-america',
    location: {
      city: 'Phoenix',
      country: 'USA',
      state: 'Arizona',
      latitude: 33.4484,
      longitude: -112.0742,
    },
    profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
    description: 'Diego coordinates mission trips to the Amazon region, helping indigenous communities with education and healthcare initiatives. He has deep connections with local leaders and a passion for reaching unreached people groups.',
    media: [
      { url: 'https://images.unsplash.com/photo-1559027615-cd5628902899?w=300', title: 'Amazon Outreach' },
      { url: 'https://images.unsplash.com/photo-1559027615-cd5628902899?w=300', title: 'Community Work' },
    ],
    contactInfo: [
      { type: 'email', value: 'diego.vargas@amazonmission.org' },
      { type: 'phone', value: '+1-602-555-0303' },
      { type: 'website', value: 'https://amazonmission.org' },
    ],
    specialNotes: 'Fluent in Spanish and indigenous languages. Expert in cross-cultural ministry.',
    startDate: '2019-03-10',
    missionType: 'Amazon Ministry',
  },
  {
    id: '4',
    name: 'Jennifer',
    lastName: 'Martinez',
    organization: 'Urban Hope Church',
    continent: 'north-america',
    location: {
      city: 'Los Angeles',
      country: 'USA',
      state: 'California',
      latitude: 34.0522,
      longitude: -118.2437,
    },
    profileImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
    description: 'Jennifer leads urban outreach programs targeting homeless populations and at-risk youth. She focuses on providing practical help combined with spiritual guidance and community support.',
    media: [
      { url: 'https://images.unsplash.com/photo-1559027615-cd5628902899?w=300', title: 'Outreach Work' },
    ],
    contactInfo: [
      { type: 'email', value: 'jennifer@urbanhope.org' },
      { type: 'phone', value: '+1-323-555-0404' },
    ],
    specialNotes: 'Specializes in urban ministry and social justice initiatives.',
    startDate: '2017-09-20',
    missionType: 'Urban Outreach',
  },
  {
    id: '5',
    name: 'Robert',
    lastName: 'Chen',
    organization: 'Medical Missions International',
    continent: 'north-america',
    location: {
      city: 'New York',
      country: 'USA',
      state: 'New York',
      latitude: 40.7128,
      longitude: -74.0060,
    },
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    description: 'Robert is a healthcare professional who combines medicine with ministry. He organizes medical clinics in underserved communities and trains local medical professionals.',
    media: [],
    contactInfo: [
      { type: 'email', value: 'robert.chen@medicalmissions.org' },
      { type: 'phone', value: '+1-212-555-0505' },
    ],
    specialNotes: 'Licensed physician. Works in underserved healthcare areas.',
    startDate: '2015-01-05',
    missionType: 'Medical Ministry',
  },
  {
    id: '6',
    name: 'Lisa',
    lastName: 'Anderson',
    organization: 'Youth for Christ',
    continent: 'north-america',
    location: {
      city: 'Chicago',
      country: 'USA',
      state: 'Illinois',
      latitude: 41.8781,
      longitude: -87.6298,
    },
    profileImage: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400',
    description: 'Lisa works with youth groups, organizing retreats, camps, and discipleship programs for teenagers. Her focus is helping youth find purpose and direction in their faith journey.',
    media: [],
    contactInfo: [
      { type: 'email', value: 'lisa@youthforchrist.org' },
      { type: 'instagram', value: 'https://instagram.com/lisaanderson' },
    ],
    specialNotes: 'Youth ministry specialist. Expert in camp and retreat planning.',
    startDate: '2016-08-12',
    missionType: 'Youth Ministry',
  },
  {
    id: '7',
    name: 'Michael',
    lastName: 'Johnson',
    organization: 'Bible Translation Service',
    continent: 'north-america',
    location: {
      city: 'Denver',
      country: 'USA',
      state: 'Colorado',
      latitude: 39.7392,
      longitude: -104.9903,
    },
    profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
    description: 'Michael leads Bible translation projects, making Scripture accessible in multiple languages. He works with churches to establish translation teams and literacy programs.',
    media: [],
    contactInfo: [
      { type: 'email', value: 'michael@bibletranslation.org' },
      { type: 'website', value: 'https://bibletranslation.org' },
    ],
    specialNotes: 'Linguist with expertise in multiple languages. Works on biblical translation.',
    startDate: '2014-02-18',
    missionType: 'Bible Translation',
  },
  {
    id: '8',
    name: 'Angela',
    lastName: 'Garcia',
    organization: 'Education Builders',
    continent: 'north-america',
    location: {
      city: 'Miami',
      country: 'USA',
      state: 'Florida',
      latitude: 25.7617,
      longitude: -80.1918,
    },
    profileImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
    description: 'Angela focuses on educational ministry, establishing schools and tutoring programs in underprivileged areas. She believes education is a pathway to spiritual and social transformation.',
    media: [],
    contactInfo: [
      { type: 'email', value: 'angela@educationbuilders.org' },
    ],
    specialNotes: 'Education specialist. Founder of three schools in underserved areas.',
    startDate: '2013-10-22',
    missionType: 'Education',
  },
  {
    id: '9',
    name: 'David',
    lastName: 'Williams',
    organization: 'Church Planting Network',
    continent: 'north-america',
    location: {
      city: 'Seattle',
      country: 'USA',
      state: 'Washington',
      latitude: 47.6062,
      longitude: -122.3321,
    },
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    description: 'David specializes in church planting initiatives, establishing new congregations in unchurched urban and rural areas. He mentors young pastors and provides resources for new church communities.',
    media: [],
    contactInfo: [
      { type: 'email', value: 'david@churchplanting.net' },
      { type: 'facebook', value: 'https://facebook.com/david.williams' },
    ],
    specialNotes: 'Has planted over 12 churches. Church planting strategy consultant.',
    startDate: '2010-05-30',
    missionType: 'Church Planting',
  },

  // South America (3)
  {
    id: '10',
    name: 'Carlos',
    lastName: 'Guzmán',
    organization: 'Latin American Mission',
    continent: 'south-america',
    location: {
      city: 'Bogotá',
      country: 'Colombia',
      latitude: 4.7110,
      longitude: -74.0721,
    },
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    description: 'Carlos serves in church development and leadership training across South America. He focuses on equipping local leaders with ministry skills and biblical knowledge.',
    media: [],
    contactInfo: [
      { type: 'email', value: 'carlos@latinamericanmission.org' },
      { type: 'phone', value: '+57-1-555-0606' },
    ],
    specialNotes: 'Serves multiple countries. Provides leadership training.',
    startDate: '2018-07-15',
    missionType: 'Church Development',
  },
  {
    id: '11',
    name: 'Isabella',
    lastName: 'Santos',
    organization: 'Women Empowerment International',
    continent: 'south-america',
    location: {
      city: 'São Paulo',
      country: 'Brazil',
      latitude: -23.5505,
      longitude: -46.6333,
    },
    profileImage: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400',
    description: 'Isabella works on women empowerment programs, teaching vocational skills, business development, and health awareness. She believes in lifting women out of poverty through education and opportunity.',
    media: [],
    contactInfo: [
      { type: 'email', value: 'isabella@womenempowerment.org' },
      { type: 'instagram', value: 'https://instagram.com/isabella_santos' },
    ],
    specialNotes: 'Entrepreneur. Founder of women\'s cooperatives.',
    startDate: '2019-03-22',
    missionType: 'Women\'s Empowerment',
  },
  {
    id: '12',
    name: 'Francisco',
    lastName: 'Mendez',
    organization: 'Community Healthcare Project',
    continent: 'south-america',
    location: {
      city: 'Lima',
      country: 'Peru',
      latitude: -12.0464,
      longitude: -77.0428,
    },
    profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
    description: 'Francisco brings healthcare to remote communities in the Andes. He combines medical care with health education and disease prevention initiatives.',
    media: [],
    contactInfo: [
      { type: 'email', value: 'francisco@communityhealthcare.org' },
      { type: 'phone', value: '+51-1-555-0707' },
    ],
    specialNotes: 'Nurse practitioner. Works in remote mountain regions.',
    startDate: '2020-01-10',
    missionType: 'Healthcare Ministry',
  },

  // Europe (3)
  {
    id: '13',
    name: 'Klaus',
    lastName: 'Mueller',
    organization: 'European Reformed Churches',
    continent: 'europe',
    location: {
      city: 'Berlin',
      country: 'Germany',
      latitude: 52.5200,
      longitude: 13.4050,
    },
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    description: 'Klaus leads interfaith dialogue and community building initiatives in post-Christian Europe. He focuses on re-evangelization and church renewal.',
    media: [],
    contactInfo: [
      { type: 'email', value: 'klaus@reformedchurches.eu' },
      { type: 'phone', value: '+49-30-555-0808' },
    ],
    specialNotes: 'Theologian. Involved in interfaith dialogue.',
    startDate: '2017-09-15',
    missionType: 'Church Renewal',
  },
  {
    id: '14',
    name: 'Margot',
    lastName: 'Dubois',
    organization: 'European Youth Network',
    continent: 'europe',
    location: {
      city: 'Paris',
      country: 'France',
      latitude: 48.8566,
      longitude: 2.3522,
    },
    profileImage: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400',
    description: 'Margot connects European youth with Christian mentorship and leadership opportunities. She organizes youth conferences and discipleship groups across France and neighboring countries.',
    media: [],
    contactInfo: [
      { type: 'email', value: 'margot@europeanyouthnetwork.org' },
      { type: 'facebook', value: 'https://facebook.com/margot.dubois' },
    ],
    specialNotes: 'Youth network coordinator. Multi-lingual.',
    startDate: '2016-05-20',
    missionType: 'Youth Ministry',
  },
  {
    id: '15',
    name: 'Dimitri',
    lastName: 'Volkov',
    organization: 'Eastern European Development',
    continent: 'europe',
    location: {
      city: 'Budapest',
      country: 'Hungary',
      latitude: 47.4979,
      longitude: 19.0402,
    },
    profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
    description: 'Dimitri works in community development and social services in Eastern Europe. He establishes shelters, job training centers, and community centers.',
    media: [],
    contactInfo: [
      { type: 'email', value: 'dimitri@easterneuropeandevelopment.org' },
      { type: 'phone', value: '+36-1-555-0909' },
    ],
    specialNotes: 'Social services expert. Established 5 community centers.',
    startDate: '2015-11-03',
    missionType: 'Community Development',
  },

  // Africa (4)
  {
    id: '16',
    name: 'Amara',
    lastName: 'Okonkwo',
    organization: 'African Christian Alliance',
    continent: 'africa',
    location: {
      city: 'Lagos',
      country: 'Nigeria',
      latitude: 6.5244,
      longitude: 3.3792,
    },
    profileImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
    description: 'Amara coordinates churches and Christian organizations across West Africa. She focuses on church leadership development and community empowerment.',
    media: [],
    contactInfo: [
      { type: 'email', value: 'amara@africanchristianalliance.org' },
      { type: 'phone', value: '+234-1-555-1010' },
    ],
    specialNotes: 'Church network coordinator. Serves multiple West African nations.',
    startDate: '2016-04-12',
    missionType: 'Church Alliance',
  },
  {
    id: '17',
    name: 'Kofi',
    lastName: 'Akosah',
    organization: 'Education for All Africa',
    continent: 'africa',
    location: {
      city: 'Accra',
      country: 'Ghana',
      latitude: 5.6037,
      longitude: -0.1870,
    },
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    description: 'Kofi builds schools and educational centers in rural Africa. He trains teachers and develops curriculum focused on both academics and Christian values.',
    media: [],
    contactInfo: [
      { type: 'email', value: 'kofi@educationforallafrica.org' },
      { type: 'phone', value: '+233-21-555-1111' },
    ],
    specialNotes: 'Education director. Built 8 schools. Teacher trainer.',
    startDate: '2014-08-18',
    missionType: 'Education',
  },
  {
    id: '18',
    name: 'Zainab',
    lastName: 'Hassan',
    organization: 'Women\'s Health Initiative Africa',
    continent: 'africa',
    location: {
      city: 'Nairobi',
      country: 'Kenya',
      latitude: -1.2865,
      longitude: 36.8172,
    },
    profileImage: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400',
    description: 'Zainab manages health clinics focusing on maternal and child health. She trains community health workers and conducts health education in rural areas.',
    media: [],
    contactInfo: [
      { type: 'email', value: 'zainab@womenshealthinitiative.org' },
      { type: 'phone', value: '+254-20-555-1212' },
    ],
    specialNotes: 'Healthcare coordinator. Specializes in maternal health.',
    startDate: '2017-06-25',
    missionType: 'Healthcare Ministry',
  },
  {
    id: '19',
    name: 'Thabo',
    lastName: 'Dlamini',
    organization: 'South African Mission Network',
    continent: 'africa',
    location: {
      city: 'Johannesburg',
      country: 'South Africa',
      latitude: -26.2023,
      longitude: 28.0436,
    },
    profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
    description: 'Thabo works with churches in post-apartheid South Africa, focusing on reconciliation, community healing, and social justice ministry.',
    media: [],
    contactInfo: [
      { type: 'email', value: 'thabo@samissionnetwork.org' },
      { type: 'facebook', value: 'https://facebook.com/thabo.dlamini' },
    ],
    specialNotes: 'Reconciliation specialist. Community organizer.',
    startDate: '2018-03-10',
    missionType: 'Reconciliation Ministry',
  },

  // Asia (5)
  {
    id: '20',
    name: 'Hiroshi',
    lastName: 'Tanaka',
    organization: 'Japan Mission Foundation',
    continent: 'asia',
    location: {
      city: 'Tokyo',
      country: 'Japan',
      latitude: 35.6762,
      longitude: 139.6503,
    },
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    description: 'Hiroshi plants churches and leads small group ministries in Japan\'s urban centers. He focuses on reaching young professionals and cultural adaptation of gospel message.',
    media: [],
    contactInfo: [
      { type: 'email', value: 'hiroshi@japanmissionfoundation.org' },
      { type: 'phone', value: '+81-3-555-1313' },
    ],
    specialNotes: 'Church planter in urban Japan. Cultural bridge-builder.',
    startDate: '2015-02-08',
    missionType: 'Church Planting',
  },
  {
    id: '21',
    name: 'Priya',
    lastName: 'Sharma',
    organization: 'Indian Christian Women\'s Network',
    continent: 'asia',
    location: {
      city: 'Delhi',
      country: 'India',
      latitude: 28.7041,
      longitude: 77.1025,
    },
    profileImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
    description: 'Priya leads women\'s empowerment and rights advocacy. She works on education, job skills, and building women\'s leadership in churches.',
    media: [],
    contactInfo: [
      { type: 'email', value: 'priya@indianchristianwomen.org' },
      { type: 'instagram', value: 'https://instagram.com/priya_sharma' },
    ],
    specialNotes: 'Women\'s rights advocate. Leadership coach.',
    startDate: '2019-01-15',
    missionType: 'Women\'s Ministry',
  },
  {
    id: '22',
    name: 'Wei',
    lastName: 'Chen',
    organization: 'Southeast Asia Christian Union',
    continent: 'asia',
    location: {
      city: 'Bangkok',
      country: 'Thailand',
      latitude: 13.7563,
      longitude: 100.5018,
    },
    profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
    description: 'Wei serves as regional coordinator for Christian organizations across Southeast Asia. He facilitates network building and collaborative ministry initiatives.',
    media: [],
    contactInfo: [
      { type: 'email', value: 'wei@seachristianunion.org' },
      { type: 'phone', value: '+66-2-555-1414' },
    ],
    specialNotes: 'Regional coordinator. Multi-country network builder.',
    startDate: '2016-09-20',
    missionType: 'Network Coordination',
  },
  {
    id: '23',
    name: 'Linh',
    lastName: 'Nguyen',
    organization: 'Vietnam Community Services',
    continent: 'asia',
    location: {
      city: 'Ho Chi Minh City',
      country: 'Vietnam',
      latitude: 10.7769,
      longitude: 106.6955,
    },
    profileImage: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400',
    description: 'Linh works in community development and disaster relief. She organizes outreach programs and trains local volunteers in compassionate ministry.',
    media: [],
    contactInfo: [
      { type: 'email', value: 'linh@vietnamcommunity.org' },
      { type: 'phone', value: '+84-28-555-1515' },
    ],
    specialNotes: 'Disaster relief coordinator. Community organizer.',
    startDate: '2017-07-30',
    missionType: 'Community Service',
  },
  {
    id: '24',
    name: 'Aishwarya',
    lastName: 'Patel',
    organization: 'South Asia Education Trust',
    continent: 'asia',
    location: {
      city: 'Mumbai',
      country: 'India',
      latitude: 19.0760,
      longitude: 72.8777,
    },
    profileImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
    description: 'Aishwarya establishes educational programs for underprivileged children. She believes education opens doors and transforms lives spiritually and socially.',
    media: [],
    contactInfo: [
      { type: 'email', value: 'aishwarya@saedtrust.org' },
      { type: 'phone', value: '+91-22-555-1616' },
    ],
    specialNotes: 'Education director. Program supervisor for 12 schools.',
    startDate: '2013-10-05',
    missionType: 'Education',
  },

  // Oceania (1)
  {
    id: '25',
    name: 'Aroha',
    lastName: 'Ngata',
    organization: 'Pacific Island Ministry Alliance',
    continent: 'oceania',
    location: {
      city: 'Auckland',
      country: 'New Zealand',
      latitude: -37.0882,
      longitude: 174.6852,
    },
    profileImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
    description: 'Aroha coordinates ministry efforts across Pacific Island nations. She works on cultural preservation and spiritual renewal within indigenous communities.',
    media: [],
    contactInfo: [
      { type: 'email', value: 'aroha@pacificislandministry.org' },
      { type: 'facebook', value: 'https://facebook.com/aroha.ngata' },
    ],
    specialNotes: 'Pacific ministry specialist. Indigenous community advocate.',
    startDate: '2014-11-12',
    missionType: 'Island Ministry',
  },
];

export const continentInfo: ContinentInfo[] = [
  {
    id: 'north-america',
    name: 'North America',
    nameSp: 'América del Norte',
    route: '/norte-america',
    centerLat: 41.35,
    centerLon: -98.99,
    color: '#2563EB',
  },
  {
    id: 'south-america',
    name: 'South America',
    nameSp: 'América del Sur',
    route: '/sur-america',
    centerLat: -8.76689,
    centerLon: -51.4728,
    color: '#4CAF50',
  },
  {
    id: 'central-america',
    name: 'Central America',
    nameSp: 'América Central',
    route: '/centro-america',
    centerLat: 15.2,
    centerLon: -86.2419,
    color: '#FF9800',
  },
  {
    id: 'europe',
    name: 'Europe',
    nameSp: 'Europa',
    route: '/europa',
    centerLat: 54.5260,
    centerLon: 15.2551,
    color: '#9C27B0',
  },
  {
    id: 'africa',
    name: 'Africa',
    nameSp: 'África',
    route: '/africa',
    centerLat: -8.7832,
    centerLon: 34.5085,
    color: '#F44336',
  },
  {
    id: 'asia',
    name: 'Asia',
    nameSp: 'Asia',
    route: '/asia',
    centerLat: 34.0479,
    centerLon: 100.6197,
    color: '#00BCD4',
  },
  {
    id: 'oceania',
    name: 'Oceania',
    nameSp: 'Oceanía',
    route: '/oceania',
    centerLat: -22.7359,
    centerLon: 140.0188,
    color: '#FFC107',
  },
];

export const getMissionariesByContinent = (continent: string): Missionary[] => {
  return mockMissionaries.filter(m => m.continent === continent);
};

export const getMissionaryById = (id: string): Missionary | undefined => {
  return mockMissionaries.find(m => m.id === id);
};

export const getMissionaryByName = (name: string, lastName: string): Missionary | undefined => {
  return mockMissionaries.find(m => m.name === name && m.lastName === lastName);
};
